In [1]:
import joblib
import pandas as pd
import numpy as np
import lightgbm as lgb
from sklearn.metrics import log_loss

**Load Data**

In [2]:
# Load from pkl
xall, yall, harai = joblib.load("./data.pkl")

In [3]:
# Input features
xall

raceid     horseid  racedate  futan  umaban  wakuban  \
0       2020010506010101  2017103291  20200105   54.0       1        1   
1       2020010506010101  2017101861  20200105   54.0       2        1   
2       2020010506010101  2017103186  20200105   54.0       3        2   
3       2020010506010101  2017102095  20200105   53.0       4        2   
4       2020010506010101  2017103287  20200105   52.0       5        3   
...                  ...         ...       ...    ...     ...      ...   
143318  2022122809060912  2018105223  20221228   53.0      12        6   
143319  2022122809060912  2017106137  20221228   56.0      13        7   
143320  2022122809060912  2017100461  20221228   56.0      14        7   
143321  2022122809060912  2018106389  20221228   52.0      15        8   
143322  2022122809060912  2019106184  20221228   53.0      16        8   

        blinker  age  bataijyu  zogen  ...  grade_5  wintime_5  lap_s3_5  \
0             0  3.0     432.0    4.0  ...     None        NaN       NaN   
1             0  3.0     424.0   -4.0  ...     None        NaN       NaN   
2             0  3.0     458.0    0.0  ...     None        NaN       NaN   
3             0  3.0     464.0   10.0  ...     None        NaN       NaN   
4             1  3.0     460.0   -2.0  ...     None        NaN       NaN   
...         ...  ...       ...    ...  ...      ...        ...       ...   
143318        0  4.0     452.0    0.0  ...        E       69.4      33.6   
143319        0  5.0     492.0    6.0  ...        E       67.3      32.8   
143320        0  5.0     504.0    4.0  ...        E       80.4      35.6   
143321        0  4.0     434.0    2.0  ...        E       68.4      33.7   
143322        0  3.0     456.0   -2.0  ...                66.8      32.4   

        lap_s4_5 lap_l3_5 lap_l4_5             f            ff             m  \
0            NaN      NaN      NaN  1.120002e+09  1.120002e+09  1.220057e+09   
1            NaN      NaN      NaN  1.120002e+09  1.140004e+09  1.220063e+09   
2            NaN      NaN      NaN  1.120002e+09  1.120002e+09  1.220061e+09   
3            NaN      NaN      NaN  1.120002e+09  1.120002e+09  1.220062e+09   
4            NaN      NaN      NaN  1.120002e+09  1.140006e+09  1.220062e+09   
...          ...      ...      ...           ...           ...           ...   
143318      45.3     35.8     46.9  1.140007e+09  1.140005e+09  1.220065e+09   
143319      44.1     34.5     45.4  1.120002e+09  1.140004e+09  1.220050e+09   
143320      47.1     33.3     44.8  1.120002e+09  1.140004e+09  1.220055e+09   
143321      45.0     34.7     45.7  1.120002e+09  1.140005e+09  1.220063e+09   
143322      43.5     34.4     45.0  1.120002e+09  1.120002e+09  1.220066e+09   

                  mf  
0       1.120002e+09  
1       1.120002e+09  
2       1.140006e+09  
3       1.120002e+09  
4       1.140005e+09  
...              ...  
143318  1.140006e+09  
143319  1.120002e+09  
143320  1.120002e+09  
143321  1.120002e+09  
143322  1.140006e+09  

[143323 rows x 224 columns]

In [4]:
# # Output feature: finishing position (0: race not finished)
yall

0          2
1         12
2          3
3         11
4          8
          ..
143318    12
143319    16
143320    11
143321     7
143322     8
Name: jyuni, Length: 143323, dtype: int64

In [5]:
# Payout
harai

RaceID TorokuTosu SyussoTosu                FuseirituFlag  \
0      2020010606010203         16         16  [0, 0, 0, 0, 0, 0, 0, 0, 0]   
1      2022010507010112         16         16  [0, 0, 0, 0, 0, 0, 0, 0, 0]   
2      2020010506010101         16         16  [0, 0, 0, 0, 0, 0, 0, 0, 0]   
3      2020010606010204         16         16  [0, 0, 0, 0, 0, 0, 0, 0, 0]   
4      2020010606010205         16         16  [0, 0, 0, 0, 0, 0, 0, 0, 0]   
...                 ...        ...        ...                          ...   
10363  2022122806050903         16         16  [0, 0, 0, 0, 0, 0, 0, 0, 0]   
10364  2022122806050902         16         16  [0, 0, 0, 0, 0, 0, 0, 0, 0]   
10365  2022122809060911         13         13  [0, 0, 0, 0, 0, 0, 0, 0, 0]   
10366  2022122806050911         18         18  [0, 0, 0, 0, 0, 0, 0, 0, 0]   
10367  2022122809060912         16         16  [0, 0, 0, 0, 0, 0, 0, 0, 0]   

                     TokubaraiFlag                   HenkanFlag  \
0      [0, 0, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 0, 0, 0, 0]   
1      [0, 0, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 0, 0, 0, 0]   
2      [0, 0, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 0, 0, 0, 0]   
3      [0, 0, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 0, 0, 0, 0]   
4      [0, 0, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 0, 0, 0, 0]   
...                            ...                          ...   
10363  [0, 0, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 0, 0, 0, 0]   
10364  [0, 0, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 0, 0, 0, 0]   
10365  [0, 0, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 0, 0, 0, 0]   
10366  [0, 0, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 0, 0, 0, 0]   
10367  [0, 0, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 0, 0, 0, 0]   

                                               HenkanUma  \
0      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
...                                                  ...   
10363  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
10364  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
10365  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
10366  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
10367  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                     HenkanWaku              HenkanDoWaku  \
0      [0, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 0, 0, 0]   
1      [0, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 0, 0, 0]   
2      [0, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 0, 0, 0]   
3      [0, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 0, 0, 0]   
4      [0, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 0, 0, 0]   
...                         ...                       ...   
10363  [0, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 0, 0, 0]   
10364  [0, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 0, 0, 0]   
10365  [0, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 0, 0, 0]   
10366  [0, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 0, 0, 0]   
10367  [0, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 0, 0, 0]   

                                               PayTansyo  ...  \
0      [{'Umaban': '09', 'Pay': '000000200', 'Ninki':...  ...   
1      [{'Umaban': '13', 'Pay': '000001530', 'Ninki':...  ...   
2      [{'Umaban': '07', 'Pay': '000000360', 'Ninki':...  ...   
3      [{'Umaban': '12', 'Pay': '000000280', 'Ninki':...  ...   
4      [{'Umaban': '07', 'Pay': '000000380', 'Ninki':...  ...   
...                                                  ...  ...   
10363  [{'Umaban': '01', 'Pay': '000000600', 'Ninki':...  ...   
10364  [{'Umaban': '04', 'Pay': '000000750', 'Ninki':...  ...   
10365  [{'Umaban': '04', 'Pay': '000000520', 'Ninki':...  ...   
10366  [{'Umaban': '11', 'Pay': '000009060', 'Ninki':...  ...   
10367  [{'Umaban': '07', 'Pay': '000000480', 'Ninki':...  ...   

                                        

In [6]:
'''
Preprocess data
'''

# Convert string values to float
for col in xall.columns:
    if xall[col].dtype == "object":
        # Convert to numeric where possible
        xall[col] = pd.to_numeric(xall[col], errors='coerce')
        # Replace NaN (from non-numeric values) with 0
        xall[col] = xall[col].fillna(0)
        print(f"Converted column: {col}")

Converted column: KisyuCode
Converted column: TozaiCD
Converted column: ChokyosiCode
Converted column: BanusiCode
Converted column: course
Converted column: cls
Converted column: grade
Converted column: BreederCode
Converted column: KisyuCode_1
Converted column: course_1
Converted column: cls_1
Converted column: grade_1
Converted column: KisyuCode_2
Converted column: course_2
Converted column: cls_2
Converted column: grade_2
Converted column: KisyuCode_3
Converted column: course_3
Converted column: cls_3
Converted column: grade_3
Converted column: KisyuCode_4
Converted column: course_4
Converted column: cls_4
Converted column: grade_4
Converted column: KisyuCode_5
Converted column: course_5
Converted column: cls_5
Converted column: grade_5


In [7]:
'''
Split into Train-Test data
'''
# Number of days to use of testing
TEST_DAYS = 90

# Date at which the data splits
rd = xall["racedate"].unique()[-TEST_DAYS] 

# split data
xtrain = xall[xall['racedate']<rd].reset_index(drop=True).copy()
ytrain = yall[xtrain.index].reset_index(drop=True).copy()
xtest = xall[xall['racedate']>=rd].reset_index(drop=True).copy()
ytest = yall[xtest.index].reset_index(drop=True).copy()

In [8]:
print(xtrain.shape, ytrain.shape, xtest.shape, ytest.shape)

(104436, 224) (104436,) (38887, 224) (38887,)


**Different models**

Each model:
- can preprocess further the dataset for its needs
- train using its dataset
- predict rankings on the test dataset

The predictions are collected in model_prediction['model_name']

In [9]:
model_prediction = {}

**Light Gradient Boosting Machine**

In [10]:
# Binarize outputs (simplify ranking to win / lose)
ytrain_lgb = ytrain.apply(lambda x: 1 if x==1 else 0)
ytest_lgb = ytest.apply(lambda x: 1 if x==1 else 0)

In [11]:
# Training parameters
num_boost_round = 100
early_stopping_round = 10
parameters = {
 'max_depth': 10,
 'min_data_in_leaf': 50,
 'learning_rate': 0.01,
 'seed': 1,
 'objective': 'binary',
 'metric': 'binary_logloss',
}

In [12]:
# Validation data (training_data=validation_data）
xtrain_val = xtrain.copy()
ytrain_val_lgb = ytrain_lgb.copy()
xtest_val = xtrain.copy()
ytest_val_lgb = ytrain_lgb.copy()

In [13]:
# Prepare dataset for LGB model
train_data_lgb = lgb.Dataset(xtrain_val, label=ytrain_val_lgb) 
valid_data_lgb = lgb.Dataset(xtest_val, label=ytest_val_lgb)

In [14]:
# Train a LGB model on our dataset
gbm = lgb.train(parameters, 
                train_data_lgb,
                valid_sets=[valid_data_lgb],
                num_boost_round=num_boost_round,
                callbacks=[lgb.early_stopping(stopping_rounds=early_stopping_round, 
                            verbose=1)]
               )

[LightGBM] [Warning] Provided parameters constrain tree depth (max_depth=10) without explicitly setting 'num_leaves'. This can lead to underfitting. To resolve this warning, pass 'num_leaves' (<=1024) in params. Alternatively, pass (max_depth=-1) and just use 'num_leaves' to constrain model complexity.
[LightGBM] [Warning] Provided parameters constrain tree depth (max_depth=10) without explicitly setting 'num_leaves'. This can lead to underfitting. To resolve this warning, pass 'num_leaves' (<=1024) in params. Alternatively, pass (max_depth=-1) and just use 'num_leaves' to constrain model complexity.
[LightGBM] [Info] Number of positive: 7532, number of negative: 96904
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.034184 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 17338
[LightGBM] [Info] Number of data points in the train set: 104436, number of used features: 212
[LightGBM] [Warning] Provided 

In [15]:
# Display feature importance
importance = pd.DataFrame(gbm.feature_importance(), index=xtrain.columns, columns=['importance'])
#importance.sort_values("importance", ascending=False)
for k, v in importance.sort_values("importance", ascending=False).iterrows():
    print(v.name, v.importance)

odds 927
goal_1 50
ChokyosiCode 49
lap_s4_5 42
odds_2 41
l3_1 33
umaban_3 29
KisyuCode 29
jyo_3 29
lap_l3_5 28
mf 28
f 28
honsyokin_1 28
lap_s3_5 27
3c_4 27
lap_l3_1 27
umaban_2 26
bataijyu_1 26
diff_1 25
raceid 25
KisyuCode_5 25
odds_3 25
m 25
time_3 24
4c_1 24
jyuryo_2 24
lap_s3_1 22
BreederCode 22
jyuni_1 22
ninki_2 21
honsyokin_3 21
odds_5 21
jyo_4 20
BanusiCode 20
lap_l4_1 20
zogen_2 20
diff_2 19
lap_s4_1 19
KisyuCode_4 19
honsyokin_4 19
lap_l3_4 18
lap_s3_3 18
lap_l3_2 17
l3_4 17
zogen_1 17
zogen 17
umaban_1 17
lap_l4_2 16
time_4 16
umaban 16
KisyuCode_1 16
goal_3 15
lap_l4_4 15
ff 15
diff_3 15
time_5 15
odds_1 15
l3_2 15
bataijyu 15
wintime_3 14
lap_s3_2 14
zogen_4 14
3c_1 14
ninki_5 14
zogen_5 13
4c_5 13
nyusen_5 13
3c_5 13
lap_s4_3 13
l3_5 13
lap_l4_5 13
umaban_5 13
goal_4 13
bataijyu_3 13
honsyokin_2 13
goal_2 12
tosu_4 12
3c_2 12
time_2 11
tenko_3 11
diff_5 11
lap_l4_3 11
odds_4 11
futan_3 11
wintime_2 11
lap_s4_2 10
jyo 10
horseid 10
tosu_2 10
lap_s4_4 9
lap_s3_4 9
ninki_3 

In [16]:
# Predict
ypred = gbm.predict(xtest)
model_prediction['LightGBM'] = ypred

**Evaluation**

In [17]:
def calc_mrr(ypred, ytrue):
    '''
    Args:
        ypred (numpy.array): predicted ranks (1 or higher) [n, MAX_HORSE]
        ytrue (numpy.array): final confirmed ranks [n, MAX_HORSE]
    
    Returns:
        mrr (int)
    '''
    res = []
    for i in range(ytrue.shape[0]):
        # Which rank did we predict for the horse that finished 1st?
        # If there is a tie, take the smallest value
        indices = np.where(ytrue[i, :] == 1) 
        if indices[0].size > 0:  # There may be races without a 1st-place horse before the start
            res.append(1 / ypred[i, np.min(indices)])
    return np.mean(res)


In [18]:
def get_reports(df_res):
    """
    Summary: 
        Outputs a report of the win predictions.

    Args:
        df_res (pd.DataFrame): Aggregated results from get_win_results

    Returns:
        None

    Note:
        Races with refunds are excluded from the aggregation
    """

    # Hit rate (accuracy)
    tekichu = df_res.apply(lambda x: sum([y in x["true"] for y in x["pred"]]) >= 1, axis=1).astype(int).values
    print("Number of races", df_res.shape[0])
    print("Number of hits", np.sum(tekichu))
    print("Hit rate", np.mean(tekichu), np.std(tekichu, ddof=1), np.std(tekichu, ddof=1) / np.sqrt(df_res.shape[0]))

    # Return rate (profitability)
    modoshi = df_res.apply(lambda x: sum([x["pay"][y] if y in x["true"] else 0 for y in x["pred"]]) + x["henkan"]*100, axis=1).values
    harai = df_res.apply(lambda x: len(x["pred"]), axis=1).values * 100
    print("Total payout", np.sum(modoshi))
    print("Return rate", np.mean(modoshi/harai), np.std(modoshi/harai, ddof=1), np.std(modoshi/harai, ddof=1) / np.sqrt(df_res.shape[0]))
    print("※Mean, standard deviation, standard error")


In [19]:
def get_win_results(df_bet, df_kekka):
    """
    Summary:
        Takes single-win bets as input, merges them with payout data, and outputs the result.

    Args:
        df_bet (pd.DataFrame): Data containing raceid and win predictions
        df_kekka (pd.DataFrame): Payout data extracted from JRA-VAN

    Returns:
        df_results (pd.DataFrame): Aggregated data for each race

    Note:
        Because ties can occur, 'true' is a list and 'pay' is a dict
    """

    # Aggregate by raceid
    res = []
    for raceid in df_bet["raceid"].tolist():
        # Get predictions
        pred = df_bet[df_bet["raceid"]==raceid]["win"].values[0]  # list of predicted horses
        # Check win or loss
        try:
            tmp = df_kekka[df_kekka.raceid==raceid].iloc[0].to_dict()  # target race
        except:
            print("Payout data for this race does not exist.", raceid)
            continue

        # Actual winners (true) and their payouts (pay)
        true = [x["Umaban"] for x in tmp["PayTansyo"] if x["Umaban"] != '  ']  # list because ties possible
        pay = {x["Umaban"]: int(x["Pay"]) for x in tmp["PayTansyo"] if x["Umaban"] != '  '}
        henkan = sum([int(tmp["HenkanUma"][x-1]) for x in pred])  # refunded amounts
        pred = [f"{x:02}" for x in pred]  # convert to string

        res.append({"pred": pred, "true": true, "pay": pay, "henkan": henkan, "raceid": raceid})     

    df_res = pd.DataFrame(res)
    get_reports(df_res)

    return df_res


In [20]:
def evaluate(xtest, ytest, ypred, harai):
    """
    Evaluate predictions for horse races.

    Args:
        xtest (pd.DataFrame): Test data containing race and horse info
        ytest (np.array): True ranks of horses
        ypred (np.array): Predicted scores for horses
        harai (pd.DataFrame): Payout data

    Returns:
        df_bet (pd.DataFrame): Betting predictions per race
        df_res (pd.DataFrame): Aggregated results with payouts
    """

    # 'jyuni': store the true ranks in a matrix of shape (num_races × 18)
    tmp = xtest.copy()
    tmp["jyuni"] = ytest
    tmp = tmp.groupby("raceid", as_index=False).apply(lambda x: x["jyuni"].values)
    jyuni = np.array([[tmp[i][j] if j < len(tmp[i]) else j+1 for j in range(18)] 
                      for i in range(tmp.shape[0])])  # padding for missing horses
    print("jyuni\n", jyuni)

    # 'pred': store the predicted ranks in a matrix of shape (num_races × 18) 
    # sorted by descending score
    tmp = xtest.copy()
    tmp["pred"] = ypred
    tmp = tmp.groupby("raceid", as_index=False).apply(
        lambda x: np.argsort(np.argsort(-x["pred"].values)) + 1
    )
    pred = np.array([[tmp[i][j] if j < len(tmp[i]) else j+1 for j in range(18)] 
                     for i in range(tmp.shape[0])])  # padding
    print("pred\n", pred)

    # Compute MRR (Mean Reciprocal Rank)
    mrr = calc_mrr(pred, jyuni)
    print("mrr\n", mrr)
        
    # df_bet: extract unique raceid rows
    df_bet = xtest[["raceid"]].groupby("raceid", as_index=False).apply(lambda x: x.iloc[0])

    # win: buy the horse ranked #1 by predicted score (single win)
    kaime = [[np.where(pred[i, :] == 1)[0][0] + 1] for i in range(pred.shape[0])]
    df_bet["win"] = kaime

    # Align payout data
    harai = harai.copy()
    harai.columns = [x.replace("RaceID", "raceid") for x in harai.columns]
    harai.raceid = harai.raceid.astype(int)

    # Compute and display results
    df_res = get_win_results(df_bet, harai)

    return df_bet, df_res


In [21]:
# Evaluate every model
results = {}

for model_name, model_ypred in model_prediction.items():
    print(f"---- Evaluating {model_name} ----")
    df_bet, df_res = evaluate(xtest, yall[xtest.index].reset_index(drop=True).copy(), model_ypred, harai)
    results[model_name] = {"df_bet": df_bet, "df_res": df_res}

---- Evaluating LightGBM ----
jyuni
 [[ 2 12  3 ... 14 17 18]
 [ 8  2  4 ...  3 17 18]
 [ 4 12  5 ...  3 17 18]
 ...
 [12 13  2 ... 16 17 18]
 [ 0 10  7 ... 16 17 18]
 [ 2  3  8 ... 12 17 18]]


/tmp/ipykernel_25766/2892576492.py:19: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  tmp = tmp.groupby("raceid", as_index=False).apply(lambda x: x["jyuni"].values)
/tmp/ipykernel_25766/2892576492.py:28: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  tmp = tmp.groupby("raceid", as_index=False).apply(
/tmp/ipykernel_25766/2892576492.py:40: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This beha

pred
 [[ 3  9  7 ...  5 17 18]
 [13 14  6 ...  9 17 18]
 [ 8 12 14 ...  3 17 18]
 ...
 [ 3  4  5 ... 16 17 18]
 [ 5  7  1 ... 16 17 18]
 [ 3  1  5 ...  7 17 18]]
mrr
 0.23596079440398804
Number of races 2856
Number of hits 976
Hit rate 0.34173669467787116 0.4743748715278793 0.008876516691665327
Total payout 235830
Return rate 0.8257352941176471 1.2432512677833703 0.023263754664889724
※Mean, standard deviation, standard error
